import { v4 as uuidv4 } from 'uuid';
import { SET_ALERT } from './types';

export const setAlert = (msg, alertType) => dispatch => {
    const id = uuidv4();

    /* Action will be dispatched to the alert reducer and an object with
     the alert message, type and ID (generated by uuid package) will be added to 
     the state */
    dispatch({
        type: SET_ALERT,
        payload: { msg, alertType, id }
    });
}